name: MonoGame Build
env:
  MONOGAME_NUGETS: MonoGame_Nugets

on: 
  push:
    tags:
      - 'v*.Pre.*'
    branches: [ main, develop ]

  pull_request:
    branches: [ main, develop ]

  workflow_dispatch:

jobs:
  build:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
      fail-fast: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Disable annotations
        run: echo "::remove-matcher owner=csc::"

      - name: Install required workloads
        run:   |
              if [ "$RUNNER_OS" == "Linux" ]; then
                    echo "MICROSOFT SUPPORT ANDROID WORKLOAD ON LINUX PLZZZ!"
              elif [ "$RUNNER_OS" == "Windows" ]; then
                    dotnet.exe workload install android ios macos
              else
                    dotnet workload install android ios macos
              fi
        shell: bash

      - if: ${{ github.event_name == 'workflow_dispatch'}}
        name: Check if tag contains '.Pre.'
        id: check_preview
        run: |
          if [[ "${GITHUB_REF}" == *".Pre."* ]]; then
            echo "is_preview=true" >> $GITHUB_OUTPUT
          else
            echo "is_preview=false" >> $GITHUB_OUTPUT
          fi

      - if: ${{ github.ref != 'refs/heads/main' }}
        name: Preview Build
        run: dotnet run --project build/Build.csproj -- --target=Default --nuget-target=preview

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Release Build
        run: dotnet run --project build/Build.csproj -- --target=Default

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Upload Artifacts
        run: dotnet run --project build/Build.csproj -- --target=UploadArtifacts
        env:
          ACTIONS_RUNTIME_TOKEN: ${{ env.ACTIONS_RUNTIME_TOKEN }}
          ACTIONS_RUNTIME_URL: "${{ env.ACTIONS_RUNTIME_URL }}"

  deploy:
      name: Deploy
      needs: [ build ]
      runs-on: ubuntu-latest
      if: ${{ github.event_name == 'workflow_dispatch' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop') }}
      permissions:
          packages: write
          contents: write
      steps:
          - name: Clone Repository
            uses: actions/checkout@v4

          - name: Setup .NET ${{ matrix.dotnet-version }}
            uses: actions/setup-dotnet@v4
            with:
              dotnet-version: '8.0.x'

          - name: Expose GitHub Runtime
            uses: crazy-max/ghaction-github-runtime@v3

          - name: Push GitHub Nugets
            run: dotnet run --project build/Build.csproj -- --target=DeployNuGetsToGithub
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          - name: Push Marketplace Nugets
            run: dotnet run --project build/Build.csproj -- --target=DeployNuGetsToMarketplace
            env:
              GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}